[package]
name = "sapphire-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Sapphire demo CLI."

[[bin]]
name = "sapphire"
path = "src/main.rs"

[dependencies]
sapphire-core.workspace = true
sapphire-keygen.workspace = true
sapphire-chain.workspace = true
sapphire-escrow.workspace = true
sapphire-node.workspace = true
frost-core.workspace = true
frost-ed25519.workspace = true
frost-rerandomized.workspace = true
reddsa = { workspace = true, features = ["frost"] }
clap.workspace = true
anyhow.workspace = true
hex.workspace = true
serde_json.workspace = true
rand.workspace = true
tracing-subscriber.workspace = true
