[package]
name = "sapphire-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Sapphire end-to-end integration tests."
publish = false

[dependencies]

[dev-dependencies]
sapphire-core = { workspace = true, features = ["redpallas"] }
sapphire-keygen.workspace = true
sapphire-signer.workspace = true
sapphire-chain.workspace = true
sapphire-validator.workspace = true
sapphire-zcash.workspace = true
sapphire-net.workspace = true
frost-core.workspace = true
frost-ed25519.workspace = true
frost-rerandomized.workspace = true
reddsa = { workspace = true, features = ["frost"] }
pasta_curves = "0.5"
ff = "0.13"
rand.workspace = true
hex.workspace = true
tokio = { workspace = true, features = ["full", "test-util", "macros", "rt-multi-thread"] }
serde_json.workspace = true
tracing-subscriber.workspace = true
