//! End-to-end FROST signing round trip via Sapphire's in-process transport.

use std::collections::BTreeMap;
use std::sync::Arc;

use frost_ed25519::Ed25519Sha512;
use rand::rngs::OsRng;

use sapphire_client::LocalTransport;
use sapphire_coordinator::{verify, Coordinator};
use sapphire_core::{protocol::KeyShareBundle, MpcParams};
use sapphire_keygen::generate_with_trusted_dealer;
use sapphire_signer::Signer;

type Cs = Ed25519Sha512;

fn build_group(
    threshold: u16,
    total: u16,
) -> (
    BTreeMap<frost_core::Identifier<Cs>, Arc<Signer<Cs>>>,
    frost_core::keys::PublicKeyPackage<Cs>,
    MpcParams,
) {
    let mut rng = OsRng;
    let params = MpcParams::new(threshold, total).unwrap();
    let (key_packages, pkp) =
        generate_with_trusted_dealer::<Cs, _>(params, &mut rng).unwrap();
    let mut signers = BTreeMap::new();
    for (id, kp) in key_packages {
        let bundle = KeyShareBundle {
            key_package: kp,
            public_key_package: pkp.clone(),
        };
        signers.insert(id, Arc::new(Signer::new(bundle)));
    }
    (signers, pkp, params)
}

#[tokio::test]
async fn two_of_three_round_trip() {
    let (signers, pkp, params) = build_group(2, 3);
    let participants: Vec<_> = signers.keys().copied().take(2).collect();
    let transport = LocalTransport::new(signers);
    let coord = Coordinator::new(params, pkp.clone());
    let mut rng = OsRng;
    let message = b"hello sapphire";
    let sig = coord
        .sign(&transport, message, &participants, &mut rng)
        .await
        .unwrap();
    verify(&pkp, message, &sig).unwrap();
}

#[tokio::test]
async fn three_of_five_round_trip() {
    let (signers, pkp, params) = build_group(3, 5);
    let participants: Vec<_> = signers.keys().copied().take(3).collect();
    let transport = LocalTransport::new(signers);
    let coord = Coordinator::new(params, pkp.clone());
    let mut rng = OsRng;
    let message = b"another message";
    let sig = coord
        .sign(&transport, message, &participants, &mut rng)
        .await
        .unwrap();
    verify(&pkp, message, &sig).unwrap();
}

#[tokio::test]
async fn below_threshold_fails() {
    let (signers, pkp, params) = build_group(3, 5);
    let participants: Vec<_> = signers.keys().copied().take(2).collect(); // only 2, need 3
    let transport = LocalTransport::new(signers);
    let coord = Coordinator::new(params, pkp);
    let mut rng = OsRng;
    let result = coord
        .sign(&transport, b"x", &participants, &mut rng)
        .await;
    assert!(result.is_err(), "expected below-threshold failure");
}

#[tokio::test]
async fn duplicate_participant_fails() {
    let (signers, pkp, params) = build_group(2, 3);
    let mut participants: Vec<_> = signers.keys().copied().take(2).collect();
    participants.push(participants[0]);
    let transport = LocalTransport::new(signers);
    let coord = Coordinator::new(params, pkp);
    let mut rng = OsRng;
    let result = coord
        .sign(&transport, b"x", &participants, &mut rng)
        .await;
    assert!(result.is_err(), "expected duplicate participant failure");
}

#[tokio::test]
async fn unknown_participant_fails() {
    let (signers, pkp, params) = build_group(2, 3);
    let participants: Vec<_> = {
        let mut ids: Vec<_> = signers.keys().copied().take(1).collect();
        // 4 is outside the 1..=3 identifier range generated by the trusted dealer.
        ids.push(frost_core::Identifier::<Cs>::try_from(4u16).unwrap());
        ids
    };
    let transport = LocalTransport::new(signers);
    let coord = Coordinator::new(params, pkp);
    let mut rng = OsRng;
    let result = coord
        .sign(&transport, b"x", &participants, &mut rng)
        .await;
    assert!(result.is_err(), "expected unknown participant failure");
}
